<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\ArchivingController;
use App\Http\Controllers\DocumentManagementController;
use App\Http\Controllers\HumanResourcesController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::controller(MainController::class)->group(function (): void {
    Route::get('/', 'root');

    Route::middleware(['auth', 'accounting.menu'])->group(function (): void {
        Route::get('/main', 'index')->name('main');
        Route::get('/main/companies/create', 'createCompany')->name('main.companies.create');
        Route::post('/main/companies', 'storeCompany')->name('main.companies.store');
        Route::get('/main/companies/{company}/edit', 'editCompany')->name('main.companies.edit');
        Route::put('/main/companies/{company}', 'updateCompany')->name('main.companies.update');
        Route::delete('/main/companies/{company}', 'destroyCompany')->name('main.companies.destroy');
        Route::get('/main/companies/{company}/sites', 'companySites')->name('main.companies.sites');
        Route::post('/main/companies/{company}/sites', 'storeCompanySite')->name('main.companies.sites.store');
        Route::get('/main/companies/{company}/sites/{site}', 'showCompanySite')->name('main.companies.sites.show');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving', [ArchivingController::class, 'dashboard'])->name('main.archiving.dashboard');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/locations', [ArchivingController::class, 'locations'])->name('main.archiving.locations');
        Route::post('/main/companies/{company}/sites/{site}/modules/archiving/locations', [ArchivingController::class, 'storeLocation'])->name('main.archiving.locations.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/archiving/locations/{type}/{location}', [ArchivingController::class, 'updateLocation'])->name('main.archiving.locations.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/archiving/locations/{type}/{location}', [ArchivingController::class, 'destroyLocation'])->name('main.archiving.locations.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/containers', [ArchivingController::class, 'containers'])->name('main.archiving.containers');
        Route::post('/main/companies/{company}/sites/{site}/modules/archiving/containers', [ArchivingController::class, 'storeContainer'])->name('main.archiving.containers.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/archiving/containers/{container}', [ArchivingController::class, 'updateContainer'])->name('main.archiving.containers.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/archiving/containers/{container}', [ArchivingController::class, 'destroyContainer'])->name('main.archiving.containers.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/records', [ArchivingController::class, 'records'])->name('main.archiving.records');
        Route::post('/main/companies/{company}/sites/{site}/modules/archiving/records', [ArchivingController::class, 'storeRecord'])->name('main.archiving.records.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/archiving/records/{record}', [ArchivingController::class, 'updateRecord'])->name('main.archiving.records.update');
        Route::post('/main/companies/{company}/sites/{site}/modules/archiving/records/{record}/file', [ArchivingController::class, 'attachRecordFile'])->name('main.archiving.records.file.attach');
        Route::post('/main/companies/{company}/sites/{site}/modules/archiving/records/{record}/file/replace', [ArchivingController::class, 'replaceRecordFile'])->name('main.archiving.records.file.replace');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/movements', [ArchivingController::class, 'movements'])->name('main.archiving.movements');
        Route::post('/main/companies/{company}/sites/{site}/modules/archiving/movements', [ArchivingController::class, 'storeMovement'])->name('main.archiving.movements.store');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/retention', [ArchivingController::class, 'retention'])->name('main.archiving.retention');
        Route::post('/main/companies/{company}/sites/{site}/modules/archiving/retention', [ArchivingController::class, 'storeRetentionRule'])->name('main.archiving.retention.store');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/traceability', [ArchivingController::class, 'traceability'])->name('main.archiving.traceability');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/reports', [ArchivingController::class, 'reports'])->name('main.archiving.reports');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/reports/pdf', [ArchivingController::class, 'printReport'])->name('main.archiving.reports.pdf');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/notifications', [ArchivingController::class, 'notifications'])->name('main.archiving.notifications');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/notifications/{notification}', [ArchivingController::class, 'showNotification'])->name('main.archiving.notifications.show');
        Route::get('/main/companies/{company}/sites/{site}/modules/archiving/settings', [ArchivingController::class, 'settings'])->name('main.archiving.settings');
        Route::put('/main/companies/{company}/sites/{site}/modules/archiving/settings', [ArchivingController::class, 'updateSettings'])->name('main.archiving.settings.update');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management', [DocumentManagementController::class, 'dashboard'])->name('main.document-management.dashboard');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/incoming', [DocumentManagementController::class, 'incoming'])->name('main.document-management.incoming');
        Route::post('/main/companies/{company}/sites/{site}/modules/document_management/incoming', [DocumentManagementController::class, 'storeIncoming'])->name('main.document-management.incoming.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/document_management/incoming/{record}', [DocumentManagementController::class, 'updateIncoming'])->name('main.document-management.incoming.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/document_management/incoming/{record}', [DocumentManagementController::class, 'destroyIncoming'])->name('main.document-management.incoming.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/outgoing', [DocumentManagementController::class, 'outgoing'])->name('main.document-management.outgoing');
        Route::post('/main/companies/{company}/sites/{site}/modules/document_management/outgoing', [DocumentManagementController::class, 'storeOutgoing'])->name('main.document-management.outgoing.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/document_management/outgoing/{record}', [DocumentManagementController::class, 'updateOutgoing'])->name('main.document-management.outgoing.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/document_management/outgoing/{record}', [DocumentManagementController::class, 'destroyOutgoing'])->name('main.document-management.outgoing.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/internal', [DocumentManagementController::class, 'internal'])->name('main.document-management.internal');
        Route::post('/main/companies/{company}/sites/{site}/modules/document_management/internal', [DocumentManagementController::class, 'storeInternal'])->name('main.document-management.internal.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/document_management/internal/{record}', [DocumentManagementController::class, 'updateInternal'])->name('main.document-management.internal.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/document_management/internal/{record}', [DocumentManagementController::class, 'destroyInternal'])->name('main.document-management.internal.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/folders', [DocumentManagementController::class, 'folders'])->name('main.document-management.folders');
        Route::post('/main/companies/{company}/sites/{site}/modules/document_management/folders', [DocumentManagementController::class, 'storeFolder'])->name('main.document-management.folders.store');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/folders/{folder}', [DocumentManagementController::class, 'showFolder'])->name('main.document-management.folders.show');
        Route::put('/main/companies/{company}/sites/{site}/modules/document_management/folders/{folder}', [DocumentManagementController::class, 'updateFolder'])->name('main.document-management.folders.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/document_management/folders/{folder}', [DocumentManagementController::class, 'destroyFolder'])->name('main.document-management.folders.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/assignments', [DocumentManagementController::class, 'assignments'])->name('main.document-management.assignments');
        Route::put('/main/companies/{company}/sites/{site}/modules/document_management/assignments/{record}', [DocumentManagementController::class, 'updateAssignment'])->name('main.document-management.assignments.update');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/traceability', [DocumentManagementController::class, 'traceability'])->name('main.document-management.traceability');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/reports', [DocumentManagementController::class, 'reports'])->name('main.document-management.reports');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/reports/pdf', [DocumentManagementController::class, 'printReport'])->name('main.document-management.reports.pdf');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/notifications', [DocumentManagementController::class, 'notifications'])->name('main.document-management.notifications');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/notifications/{notification}', [DocumentManagementController::class, 'showNotification'])->name('main.document-management.notifications.show');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/settings', [DocumentManagementController::class, 'settings'])->name('main.document-management.settings');
        Route::put('/main/companies/{company}/sites/{site}/modules/document_management/settings', [DocumentManagementController::class, 'updateSettings'])->name('main.document-management.settings.update');
        Route::get('/main/companies/{company}/sites/{site}/modules/document_management/validation-circuits', [DocumentManagementController::class, 'validationCircuits'])->name('main.document-management.validation-circuits');
        Route::post('/main/companies/{company}/sites/{site}/modules/document_management/validation-circuits', [DocumentManagementController::class, 'storeValidationCircuit'])->name('main.document-management.validation-circuits.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/document_management/validation-circuits/{circuit}', [DocumentManagementController::class, 'updateValidationCircuit'])->name('main.document-management.validation-circuits.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/document_management/validation-circuits/{circuit}', [DocumentManagementController::class, 'destroyValidationCircuit'])->name('main.document-management.validation-circuits.destroy');
        Route::post('/main/companies/{company}/sites/{site}/modules/document_management/validation-requests', [DocumentManagementController::class, 'storeValidationRequest'])->name('main.document-management.validation-requests.store');
        Route::post('/main/companies/{company}/sites/{site}/modules/document_management/validation-requests/{validationRequest}/approve', [DocumentManagementController::class, 'approveValidationRequest'])->name('main.document-management.validation-requests.approve');
        Route::post('/main/companies/{company}/sites/{site}/modules/document_management/validation-requests/{validationRequest}/reject', [DocumentManagementController::class, 'rejectValidationRequest'])->name('main.document-management.validation-requests.reject');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources', [HumanResourcesController::class, 'dashboard'])->name('main.human-resources.dashboard');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/employees', [HumanResourcesController::class, 'employees'])->name('main.human-resources.employees');
        Route::post('/main/companies/{company}/sites/{site}/modules/human_resources/employees', [HumanResourcesController::class, 'storeEmployee'])->name('main.human-resources.employees.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/human_resources/employees/{employee}', [HumanResourcesController::class, 'updateEmployee'])->name('main.human-resources.employees.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/human_resources/employees/{employee}', [HumanResourcesController::class, 'destroyEmployee'])->name('main.human-resources.employees.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/departments', [HumanResourcesController::class, 'departments'])->name('main.human-resources.departments');
        Route::post('/main/companies/{company}/sites/{site}/modules/human_resources/departments', [HumanResourcesController::class, 'storeDepartment'])->name('main.human-resources.departments.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/human_resources/departments/{department}', [HumanResourcesController::class, 'updateDepartment'])->name('main.human-resources.departments.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/human_resources/departments/{department}', [HumanResourcesController::class, 'destroyDepartment'])->name('main.human-resources.departments.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/attendance', [HumanResourcesController::class, 'attendance'])->name('main.human-resources.attendance');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/attendance/report/pdf', [HumanResourcesController::class, 'printAttendanceReport'])->name('main.human-resources.attendance.report.pdf');
        Route::post('/main/companies/{company}/sites/{site}/modules/human_resources/attendance', [HumanResourcesController::class, 'storeAttendance'])->name('main.human-resources.attendance.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/human_resources/attendance/{attendance}', [HumanResourcesController::class, 'updateAttendance'])->name('main.human-resources.attendance.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/human_resources/attendance/{attendance}', [HumanResourcesController::class, 'destroyAttendance'])->name('main.human-resources.attendance.destroy');
        Route::post('/main/companies/{company}/sites/{site}/modules/human_resources/attendance/import', [HumanResourcesController::class, 'importAttendance'])->name('main.human-resources.attendance.import');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/contracts', [HumanResourcesController::class, 'contracts'])->name('main.human-resources.contracts');
        Route::post('/main/companies/{company}/sites/{site}/modules/human_resources/contracts', [HumanResourcesController::class, 'storeContract'])->name('main.human-resources.contracts.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/human_resources/contracts/{contract}', [HumanResourcesController::class, 'updateContract'])->name('main.human-resources.contracts.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/human_resources/contracts/{contract}', [HumanResourcesController::class, 'destroyContract'])->name('main.human-resources.contracts.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/leave', [HumanResourcesController::class, 'leave'])->name('main.human-resources.leave');
        Route::post('/main/companies/{company}/sites/{site}/modules/human_resources/leave', [HumanResourcesController::class, 'storeLeave'])->name('main.human-resources.leave.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/human_resources/leave/{leave}', [HumanResourcesController::class, 'updateLeave'])->name('main.human-resources.leave.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/human_resources/leave/{leave}', [HumanResourcesController::class, 'destroyLeave'])->name('main.human-resources.leave.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/notifications', [HumanResourcesController::class, 'notifications'])->name('main.human-resources.notifications');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/notifications/{notification}', [HumanResourcesController::class, 'showNotification'])->name('main.human-resources.notifications.show');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/payroll', [HumanResourcesController::class, 'payroll'])->name('main.human-resources.payroll');
        Route::post('/main/companies/{company}/sites/{site}/modules/human_resources/payroll', [HumanResourcesController::class, 'storePayroll'])->name('main.human-resources.payroll.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/human_resources/payroll/{payroll}', [HumanResourcesController::class, 'updatePayroll'])->name('main.human-resources.payroll.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/human_resources/payroll/{payroll}', [HumanResourcesController::class, 'destroyPayroll'])->name('main.human-resources.payroll.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/reports', [HumanResourcesController::class, 'reports'])->name('main.human-resources.reports');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/reports/pdf', [HumanResourcesController::class, 'printReport'])->name('main.human-resources.reports.pdf');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/settings', [HumanResourcesController::class, 'settings'])->name('main.human-resources.settings');
        Route::put('/main/companies/{company}/sites/{site}/modules/human_resources/settings', [HumanResourcesController::class, 'updateSettings'])->name('main.human-resources.settings.update');
        Route::get('/main/companies/{company}/sites/{site}/modules/human_resources/{hrResource}', [HumanResourcesController::class, 'resourcePage'])
            ->whereIn('hrResource', ['documents', 'salary-advances', 'payroll-adjustments', 'schedules', 'evaluations', 'trainings', 'sanctions', 'recruitment'])
            ->name('main.human-resources.resources');
        Route::post('/main/companies/{company}/sites/{site}/modules/human_resources/{hrResource}', [HumanResourcesController::class, 'storeResource'])
            ->whereIn('hrResource', ['documents', 'salary-advances', 'payroll-adjustments', 'schedules', 'evaluations', 'trainings', 'sanctions', 'recruitment'])
            ->name('main.human-resources.resources.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/human_resources/{hrResource}/{record}', [HumanResourcesController::class, 'updateResource'])
            ->whereIn('hrResource', ['documents', 'salary-advances', 'payroll-adjustments', 'schedules', 'evaluations', 'trainings', 'sanctions', 'recruitment'])
            ->name('main.human-resources.resources.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/human_resources/{hrResource}/{record}', [HumanResourcesController::class, 'destroyResource'])
            ->whereIn('hrResource', ['documents', 'salary-advances', 'payroll-adjustments', 'schedules', 'evaluations', 'trainings', 'sanctions', 'recruitment'])
            ->name('main.human-resources.resources.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/{module}', 'showSiteModule')->name('main.companies.sites.modules.show');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/clients', 'accountingClients')->name('main.accounting.clients');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/clients', 'storeAccountingClient')->name('main.accounting.clients.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/clients/{client}', 'updateAccountingClient')->name('main.accounting.clients.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/clients/{client}', 'destroyAccountingClient')->name('main.accounting.clients.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/prospects', 'accountingProspects')->name('main.accounting.prospects');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/prospects', 'storeAccountingProspect')->name('main.accounting.prospects.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/prospects/{prospect}', 'updateAccountingProspect')->name('main.accounting.prospects.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/prospects/{prospect}', 'destroyAccountingProspect')->name('main.accounting.prospects.destroy');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/prospects/{prospect}/convert', 'convertAccountingProspect')->name('main.accounting.prospects.convert');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/suppliers', 'accountingSuppliers')->name('main.accounting.suppliers');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/suppliers', 'storeAccountingSupplier')->name('main.accounting.suppliers.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/suppliers/{supplier}', 'updateAccountingSupplier')->name('main.accounting.suppliers.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/suppliers/{supplier}', 'destroyAccountingSupplier')->name('main.accounting.suppliers.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/creditors', 'accountingCreditors')->name('main.accounting.creditors');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/creditors', 'storeAccountingCreditor')->name('main.accounting.creditors.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/creditors/{creditor}', 'updateAccountingCreditor')->name('main.accounting.creditors.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/creditors/{creditor}', 'destroyAccountingCreditor')->name('main.accounting.creditors.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/debtors', 'accountingDebtors')->name('main.accounting.debtors');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/debtors', 'storeAccountingDebtor')->name('main.accounting.debtors.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/debtors/{debtor}', 'updateAccountingDebtor')->name('main.accounting.debtors.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/debtors/{debtor}', 'destroyAccountingDebtor')->name('main.accounting.debtors.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/partners', 'accountingPartners')->name('main.accounting.partners');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/partners', 'storeAccountingPartner')->name('main.accounting.partners.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/partners/{partner}', 'updateAccountingPartner')->name('main.accounting.partners.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/partners/{partner}', 'destroyAccountingPartner')->name('main.accounting.partners.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/sales-representatives', 'accountingSalesRepresentatives')->name('main.accounting.sales-representatives');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/sales-representatives', 'storeAccountingSalesRepresentative')->name('main.accounting.sales-representatives.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/sales-representatives/{representative}', 'updateAccountingSalesRepresentative')->name('main.accounting.sales-representatives.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/sales-representatives/{representative}', 'destroyAccountingSalesRepresentative')->name('main.accounting.sales-representatives.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/currencies', 'accountingCurrencies')->name('main.accounting.currencies');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/currencies', 'storeAccountingCurrency')->name('main.accounting.currencies.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/currencies/{currency}', 'updateAccountingCurrency')->name('main.accounting.currencies.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/currencies/{currency}', 'destroyAccountingCurrency')->name('main.accounting.currencies.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/payment-methods', 'accountingPaymentMethods')->name('main.accounting.payment-methods');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/payment-methods', 'storeAccountingPaymentMethod')->name('main.accounting.payment-methods.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/payment-methods/{method}', 'updateAccountingPaymentMethod')->name('main.accounting.payment-methods.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/payment-methods/{method}', 'destroyAccountingPaymentMethod')->name('main.accounting.payment-methods.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/taxes', 'accountingTaxes')->name('main.accounting.taxes');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/taxes', 'storeAccountingTax')->name('main.accounting.taxes.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/taxes/{tax}', 'updateAccountingTax')->name('main.accounting.taxes.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/taxes/{tax}', 'destroyAccountingTax')->name('main.accounting.taxes.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/treasury', 'accountingTreasury')->name('main.accounting.treasury');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations', 'accountingBankReconciliations')->name('main.accounting.bank-reconciliations');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations', 'storeAccountingBankReconciliation')->name('main.accounting.bank-reconciliations.store');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations/{reconciliation}/lines', 'storeAccountingBankStatementLine')->name('main.accounting.bank-reconciliations.lines.store');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations/{reconciliation}/import', 'importAccountingBankStatement')->name('main.accounting.bank-reconciliations.import');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations/{reconciliation}/lines/{line}/match', 'matchAccountingBankStatementLine')->name('main.accounting.bank-reconciliations.lines.match');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations/{reconciliation}/lines/{line}/match', 'unmatchAccountingBankStatementLine')->name('main.accounting.bank-reconciliations.lines.unmatch');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations/{reconciliation}/lines/{line}/adjustment', 'createAccountingBankStatementAdjustment')->name('main.accounting.bank-reconciliations.lines.adjustment');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations/{reconciliation}/lines/{line}/ignore', 'ignoreAccountingBankStatementLine')->name('main.accounting.bank-reconciliations.lines.ignore');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations/{reconciliation}/close', 'closeAccountingBankReconciliation')->name('main.accounting.bank-reconciliations.close');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/bank-reconciliations/{reconciliation}/report', 'printAccountingBankReconciliation')->name('main.accounting.bank-reconciliations.report');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/payment-reminders', 'accountingPaymentReminders')->name('main.accounting.payment-reminders');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/payment-reminders', 'storeAccountingPaymentReminder')->name('main.accounting.payment-reminders.store');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/payment-reminders/{reminder}/promises', 'storeAccountingPaymentPromise')->name('main.accounting.payment-reminders.promises.store');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/payment-reminders/{reminder}/dispute', 'disputeAccountingPaymentReminder')->name('main.accounting.payment-reminders.dispute');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/payment-reminders/{reminder}/suspend', 'suspendAccountingPaymentReminder')->name('main.accounting.payment-reminders.suspend');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/payment-reminders/{reminder}/letter', 'printAccountingPaymentReminder')->name('main.accounting.payment-reminders.letter');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/tasks', 'accountingTasks')->name('main.accounting.tasks');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/tasks', 'storeAccountingTask')->name('main.accounting.tasks.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/tasks/{task}', 'updateAccountingTask')->name('main.accounting.tasks.update');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/tasks/{task}/complete', 'completeAccountingTask')->name('main.accounting.tasks.complete');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/tasks/{task}', 'destroyAccountingTask')->name('main.accounting.tasks.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/reports', 'accountingReports')->name('main.accounting.reports');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/reports/pdf', 'printAccountingReport')->name('main.accounting.reports.pdf');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/reports/export', 'exportAccountingReport')->name('main.accounting.reports.export');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/notifications', 'accountingNotifications')->name('main.accounting.notifications');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/notifications/{notification}', 'showAccountingNotification')->name('main.accounting.notifications.show');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/settings', 'accountingSettings')->name('main.accounting.settings');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/settings', 'updateAccountingSettings')->name('main.accounting.settings.update');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/proforma-invoices', 'accountingProformaInvoices')->name('main.accounting.proforma-invoices');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/proforma-invoices/create', 'createAccountingProformaInvoice')->name('main.accounting.proforma-invoices.create');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/proforma-invoices/import-quote', 'importAccountingProformaQuote')->name('main.accounting.proforma-invoices.import-quote');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/proforma-invoices', 'storeAccountingProformaInvoice')->name('main.accounting.proforma-invoices.store');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/proforma-invoices/{proforma}/edit', 'editAccountingProformaInvoice')->name('main.accounting.proforma-invoices.edit');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/proforma-invoices/{proforma}/print', 'printAccountingProformaInvoice')->name('main.accounting.proforma-invoices.print');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/proforma-invoices/{proforma}/convert-to-order', 'convertAccountingProformaToCustomerOrder')->name('main.accounting.proforma-invoices.convert-to-order');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/proforma-invoices/{proforma}', 'updateAccountingProformaInvoice')->name('main.accounting.proforma-invoices.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/proforma-invoices/{proforma}', 'destroyAccountingProformaInvoice')->name('main.accounting.proforma-invoices.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/customer-orders', 'accountingCustomerOrders')->name('main.accounting.customer-orders');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/customer-orders/create', 'createAccountingCustomerOrder')->name('main.accounting.customer-orders.create');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/customer-orders', 'storeAccountingCustomerOrder')->name('main.accounting.customer-orders.store');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/customer-orders/{order}/edit', 'editAccountingCustomerOrder')->name('main.accounting.customer-orders.edit');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/customer-orders/{order}', 'updateAccountingCustomerOrder')->name('main.accounting.customer-orders.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/customer-orders/{order}', 'destroyAccountingCustomerOrder')->name('main.accounting.customer-orders.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/delivery-notes', 'accountingDeliveryNotes')->name('main.accounting.delivery-notes');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/delivery-notes/create', 'createAccountingDeliveryNote')->name('main.accounting.delivery-notes.create');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/delivery-notes', 'storeAccountingDeliveryNote')->name('main.accounting.delivery-notes.store');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/delivery-notes/{deliveryNote}/print', 'printAccountingDeliveryNote')->name('main.accounting.delivery-notes.print');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/delivery-notes/{deliveryNote}', 'destroyAccountingDeliveryNote')->name('main.accounting.delivery-notes.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/sales-invoices', 'accountingSalesInvoices')->name('main.accounting.sales-invoices');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/receipts', 'accountingReceipts')->name('main.accounting.receipts');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/other-incomes', 'accountingOtherIncomes')->name('main.accounting.other-incomes');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/other-incomes', 'storeAccountingOtherIncome')->name('main.accounting.other-incomes.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/other-incomes/{income}', 'updateAccountingOtherIncome')->name('main.accounting.other-incomes.update');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/other-incomes/{income}/validate', 'validateAccountingOtherIncome')->name('main.accounting.other-incomes.validate');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/other-incomes/{income}/cancel', 'cancelAccountingOtherIncome')->name('main.accounting.other-incomes.cancel');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/other-incomes/{income}', 'destroyAccountingOtherIncome')->name('main.accounting.other-incomes.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/expenses', 'accountingExpenses')->name('main.accounting.expenses');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/expenses', 'storeAccountingExpense')->name('main.accounting.expenses.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/expenses/{expense}', 'updateAccountingExpense')->name('main.accounting.expenses.update');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/expenses/{expense}/validate', 'validateAccountingExpense')->name('main.accounting.expenses.validate');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/expenses/{expense}/cancel', 'cancelAccountingExpense')->name('main.accounting.expenses.cancel');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/expenses/{expense}', 'destroyAccountingExpense')->name('main.accounting.expenses.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/debts', 'accountingDebts')->name('main.accounting.debts');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/debts', 'storeAccountingDebt')->name('main.accounting.debts.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/debts/{creditor}', 'updateAccountingDebt')->name('main.accounting.debts.update');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/debts/{creditor}/payments', 'storeAccountingDebtPayment')->name('main.accounting.debts.payments.store');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/debts/{creditor}', 'destroyAccountingDebt')->name('main.accounting.debts.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/receivables', 'accountingReceivables')->name('main.accounting.receivables');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/receivables', 'storeAccountingReceivable')->name('main.accounting.receivables.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/receivables/{debtor}', 'updateAccountingReceivable')->name('main.accounting.receivables.update');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/receivables/{debtor}/payments', 'storeAccountingReceivablePayment')->name('main.accounting.receivables.payments.store');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/receivables/{debtor}', 'destroyAccountingReceivable')->name('main.accounting.receivables.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/purchases', 'accountingPurchases')->name('main.accounting.purchases');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/purchase-orders', 'accountingPurchaseOrders')->name('main.accounting.purchase-orders');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/purchase-orders/create', 'createAccountingPurchaseOrder')->name('main.accounting.purchase-orders.create');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/purchase-orders', 'storeAccountingPurchaseOrder')->name('main.accounting.purchase-orders.store');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/purchase-orders/{purchaseOrder}/edit', 'editAccountingPurchaseOrder')->name('main.accounting.purchase-orders.edit');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/purchase-orders/{purchaseOrder}', 'updateAccountingPurchaseOrder')->name('main.accounting.purchase-orders.update');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/purchase-orders/{purchaseOrder}/print', 'printAccountingPurchaseOrder')->name('main.accounting.purchase-orders.print');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/purchase-orders/{purchaseOrder}/convert', 'convertAccountingPurchaseOrderToPurchase')->name('main.accounting.purchase-orders.convert');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/purchase-orders/{purchaseOrder}', 'destroyAccountingPurchaseOrder')->name('main.accounting.purchase-orders.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/purchases/create', 'createAccountingPurchase')->name('main.accounting.purchases.create');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/purchases', 'storeAccountingPurchase')->name('main.accounting.purchases.store');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/purchases/{purchase}/edit', 'editAccountingPurchase')->name('main.accounting.purchases.edit');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/purchases/{purchase}', 'updateAccountingPurchase')->name('main.accounting.purchases.update');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/purchases/{purchase}/payments', 'storeAccountingPurchasePayment')->name('main.accounting.purchases.payments.store');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/purchases/{purchase}', 'destroyAccountingPurchase')->name('main.accounting.purchases.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/cash-register', 'accountingCashRegister')->name('main.accounting.cash-register');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/cash-register/open', 'openAccountingCashRegisterSession')->name('main.accounting.cash-register.open');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/cash-register', 'storeAccountingCashRegisterSale')->name('main.accounting.cash-register.store');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/cash-register/sessions/{session}/close', 'closeAccountingCashRegisterSession')->name('main.accounting.cash-register.close');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/cash-register/sessions/{session}/report', 'printAccountingCashRegisterSession')->name('main.accounting.cash-register.report');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/sales-invoices/create', 'createAccountingSalesInvoice')->name('main.accounting.sales-invoices.create');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/sales-invoices', 'storeAccountingSalesInvoice')->name('main.accounting.sales-invoices.store');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/sales-invoices/{invoice}/edit', 'editAccountingSalesInvoice')->name('main.accounting.sales-invoices.edit');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/sales-invoices/{invoice}', 'updateAccountingSalesInvoice')->name('main.accounting.sales-invoices.update');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/sales-invoices/{invoice}/print', 'printAccountingSalesInvoice')->name('main.accounting.sales-invoices.print');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/sales-invoices/{invoice}/payments', 'storeAccountingSalesInvoicePayment')->name('main.accounting.sales-invoices.payments.store');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/sales-invoices/{invoice}', 'destroyAccountingSalesInvoice')->name('main.accounting.sales-invoices.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/credit-notes', 'accountingCreditNotes')->name('main.accounting.credit-notes');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/credit-notes/create', 'createAccountingCreditNote')->name('main.accounting.credit-notes.create');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/credit-notes', 'storeAccountingCreditNote')->name('main.accounting.credit-notes.store');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/credit-notes/{creditNote}/validate', 'validateAccountingCreditNote')->name('main.accounting.credit-notes.validate');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/credit-notes/{creditNote}/cancel', 'cancelAccountingCreditNote')->name('main.accounting.credit-notes.cancel');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/credit-notes/{creditNote}/print', 'printAccountingCreditNote')->name('main.accounting.credit-notes.print');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/credit-notes/{creditNote}', 'destroyAccountingCreditNote')->name('main.accounting.credit-notes.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/stock/{resource}', 'accountingStockIndex')->name('main.accounting.stock.index');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/stock/{resource}', 'storeAccountingStockResource')->name('main.accounting.stock.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/stock/{resource}/{record}', 'updateAccountingStockResource')->name('main.accounting.stock.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/stock/{resource}/{record}', 'destroyAccountingStockResource')->name('main.accounting.stock.destroy');
        Route::get('/main/companies/{company}/sites/{site}/modules/accounting/services/{resource}', 'accountingServiceIndex')->name('main.accounting.services.index');
        Route::post('/main/companies/{company}/sites/{site}/modules/accounting/services/{resource}', 'storeAccountingServiceResource')->name('main.accounting.services.store');
        Route::put('/main/companies/{company}/sites/{site}/modules/accounting/services/{resource}/{record}', 'updateAccountingServiceResource')->name('main.accounting.services.update');
        Route::delete('/main/companies/{company}/sites/{site}/modules/accounting/services/{resource}/{record}', 'destroyAccountingServiceResource')->name('main.accounting.services.destroy');
        Route::put('/main/companies/{company}/sites/{site}', 'updateCompanySite')->name('main.companies.sites.update');
        Route::delete('/main/companies/{company}/sites/{site}', 'destroyCompanySite')->name('main.companies.sites.destroy');
        Route::get('/main/users', 'users')->name('main.users');
        Route::post('/main/users', 'storeUser')->name('main.users.store');
        Route::get('/main/users/{account}/login-history', 'userLoginHistory')->name('main.users.login-history');
        Route::put('/main/users/{account}', 'updateUser')->name('main.users.update');
        Route::delete('/main/users/{account}', 'destroyUser')->name('main.users.destroy');
    });
});

Route::prefix('admin')
    ->name('admin.')
    ->middleware(['auth', 'superadmin'])
    ->controller(AdminController::class)
    ->group(function (): void {
        Route::get('/dashboard', 'dashboard')->name('dashboard');
        Route::get('/subscriptions', 'subscriptions')->name('subscriptions');
        Route::get('/users', 'users')->name('users');
        Route::get('/users/{account}/login-history', 'userLoginHistory')->name('users.login-history');
        Route::get('/companies', 'companies')->name('companies');
        Route::get('/application-settings', 'applicationSettings')->name('application-settings');
        Route::put('/application-settings', 'updateApplicationSettings')->name('application-settings.update');
        Route::get('/companies/create', 'createCompany')->name('companies.create');
        Route::post('/companies', 'storeCompany')->name('companies.store');
        Route::get('/companies/{company}/edit', 'editCompany')->name('companies.edit');
        Route::put('/companies/{company}', 'updateCompany')->name('companies.update');
        Route::delete('/companies/{company}', 'destroyCompany')->name('companies.destroy');
        Route::post('/users', 'storeUser')->name('users.store');
        Route::put('/users/{account}', 'updateUser')->name('users.update');
        Route::delete('/users/{account}', 'destroyUser')->name('users.destroy');
        Route::post('/admins', 'storeAdmin')->name('admins.store');
        Route::post('/subscriptions', 'storeSubscription')->name('subscriptions.store');
        Route::put('/subscriptions/{subscription}', 'updateSubscription')->name('subscriptions.update');
        Route::delete('/subscriptions/{subscription}', 'destroySubscription')->name('subscriptions.destroy');
    });

Route::controller(LanguageController::class)->group(function (): void {
    Route::get('/lang/{locale}', 'switch')->name('locale.switch');
});

Route::middleware('auth')->controller(ProfileController::class)->group(function (): void {
    Route::get('/profile', 'edit')->name('profile.edit');
    Route::put('/profile/photo', 'updatePhoto')->name('profile.photo.update');
    Route::put('/profile/information', 'updateInformation')->name('profile.information.update');
    Route::put('/profile/email', 'updateEmail')->name('profile.email.update');
    Route::put('/profile/password', 'updatePassword')->name('profile.password.update');
    Route::post('/profile/two-factor', 'enableTwoFactor')->name('profile.two-factor.enable');
    Route::post('/profile/two-factor/confirm', 'confirmTwoFactor')->name('profile.two-factor.confirm');
    Route::delete('/profile/two-factor', 'disableTwoFactor')->name('profile.two-factor.disable');
});
