<?php

/*
|--------------------------------------------------------------------------
| Currency reference data
|--------------------------------------------------------------------------
|
| ISO 4217 currency codes used by the ERP when creating company bank
| accounts. Names are display labels only; the saved value is the ISO code.
|
*/

$currencies = [
    'AED' => ['name_fr' => 'Dirham des Émirats arabes unis', 'name_en' => 'United Arab Emirates dirham'],
    'AFN' => ['name_fr' => 'Afghani afghan', 'name_en' => 'Afghan afghani'],
    'ALL' => ['name_fr' => 'Lek albanais', 'name_en' => 'Albanian lek'],
    'AMD' => ['name_fr' => 'Dram arménien', 'name_en' => 'Armenian dram'],
    'ANG' => ['name_fr' => 'Florin antillais', 'name_en' => 'Netherlands Antillean guilder'],
    'AOA' => ['name_fr' => 'Kwanza angolais', 'name_en' => 'Angolan kwanza'],
    'ARS' => ['name_fr' => 'Peso argentin', 'name_en' => 'Argentine peso'],
    'AUD' => ['name_fr' => 'Dollar australien', 'name_en' => 'Australian dollar'],
    'AWG' => ['name_fr' => 'Florin arubais', 'name_en' => 'Aruban florin'],
    'AZN' => ['name_fr' => 'Manat azerbaïdjanais', 'name_en' => 'Azerbaijani manat'],
    'BAM' => ['name_fr' => 'Mark convertible de Bosnie-Herzégovine', 'name_en' => 'Bosnia and Herzegovina convertible mark'],
    'BBD' => ['name_fr' => 'Dollar barbadien', 'name_en' => 'Barbadian dollar'],
    'BDT' => ['name_fr' => 'Taka bangladais', 'name_en' => 'Bangladeshi taka'],
    'BGN' => ['name_fr' => 'Lev bulgare', 'name_en' => 'Bulgarian lev'],
    'BHD' => ['name_fr' => 'Dinar bahreïni', 'name_en' => 'Bahraini dinar'],
    'BIF' => ['name_fr' => 'Franc burundais', 'name_en' => 'Burundian franc'],
    'BMD' => ['name_fr' => 'Dollar bermudien', 'name_en' => 'Bermudian dollar'],
    'BND' => ['name_fr' => 'Dollar brunéien', 'name_en' => 'Brunei dollar'],
    'BOB' => ['name_fr' => 'Boliviano bolivien', 'name_en' => 'Bolivian boliviano'],
    'BRL' => ['name_fr' => 'Réal brésilien', 'name_en' => 'Brazilian real'],
    'BSD' => ['name_fr' => 'Dollar bahaméen', 'name_en' => 'Bahamian dollar'],
    'BTN' => ['name_fr' => 'Ngultrum bhoutanais', 'name_en' => 'Bhutanese ngultrum'],
    'BWP' => ['name_fr' => 'Pula botswanais', 'name_en' => 'Botswana pula'],
    'BYN' => ['name_fr' => 'Rouble biélorusse', 'name_en' => 'Belarusian ruble'],
    'BZD' => ['name_fr' => 'Dollar bélizien', 'name_en' => 'Belize dollar'],
    'CAD' => ['name_fr' => 'Dollar canadien', 'name_en' => 'Canadian dollar'],
    'CDF' => ['name_fr' => 'Franc congolais', 'name_en' => 'Congolese franc'],
    'CHF' => ['name_fr' => 'Franc suisse', 'name_en' => 'Swiss franc'],
    'CLP' => ['name_fr' => 'Peso chilien', 'name_en' => 'Chilean peso'],
    'CNY' => ['name_fr' => 'Yuan renminbi chinois', 'name_en' => 'Chinese yuan renminbi'],
    'COP' => ['name_fr' => 'Peso colombien', 'name_en' => 'Colombian peso'],
    'CRC' => ['name_fr' => 'Colón costaricien', 'name_en' => 'Costa Rican colon'],
    'CUP' => ['name_fr' => 'Peso cubain', 'name_en' => 'Cuban peso'],
    'CVE' => ['name_fr' => 'Escudo cap-verdien', 'name_en' => 'Cape Verdean escudo'],
    'CZK' => ['name_fr' => 'Couronne tchèque', 'name_en' => 'Czech koruna'],
    'DJF' => ['name_fr' => 'Franc djiboutien', 'name_en' => 'Djiboutian franc'],
    'DKK' => ['name_fr' => 'Couronne danoise', 'name_en' => 'Danish krone'],
    'DOP' => ['name_fr' => 'Peso dominicain', 'name_en' => 'Dominican peso'],
    'DZD' => ['name_fr' => 'Dinar algérien', 'name_en' => 'Algerian dinar'],
    'EGP' => ['name_fr' => 'Livre égyptienne', 'name_en' => 'Egyptian pound'],
    'ERN' => ['name_fr' => 'Nakfa érythréen', 'name_en' => 'Eritrean nakfa'],
    'ETB' => ['name_fr' => 'Birr éthiopien', 'name_en' => 'Ethiopian birr'],
    'EUR' => ['name_fr' => 'Euro', 'name_en' => 'Euro'],
    'FJD' => ['name_fr' => 'Dollar fidjien', 'name_en' => 'Fijian dollar'],
    'FKP' => ['name_fr' => 'Livre des îles Malouines', 'name_en' => 'Falkland Islands pound'],
    'GBP' => ['name_fr' => 'Livre sterling', 'name_en' => 'Pound sterling'],
    'GEL' => ['name_fr' => 'Lari géorgien', 'name_en' => 'Georgian lari'],
    'GHS' => ['name_fr' => 'Cedi ghanéen', 'name_en' => 'Ghanaian cedi'],
    'GIP' => ['name_fr' => 'Livre de Gibraltar', 'name_en' => 'Gibraltar pound'],
    'GMD' => ['name_fr' => 'Dalasi gambien', 'name_en' => 'Gambian dalasi'],
    'GNF' => ['name_fr' => 'Franc guinéen', 'name_en' => 'Guinean franc'],
    'GTQ' => ['name_fr' => 'Quetzal guatémaltèque', 'name_en' => 'Guatemalan quetzal'],
    'GYD' => ['name_fr' => 'Dollar guyanien', 'name_en' => 'Guyanese dollar'],
    'HKD' => ['name_fr' => 'Dollar de Hong Kong', 'name_en' => 'Hong Kong dollar'],
    'HNL' => ['name_fr' => 'Lempira hondurien', 'name_en' => 'Honduran lempira'],
    'HTG' => ['name_fr' => 'Gourde haïtienne', 'name_en' => 'Haitian gourde'],
    'HUF' => ['name_fr' => 'Forint hongrois', 'name_en' => 'Hungarian forint'],
    'IDR' => ['name_fr' => 'Roupie indonésienne', 'name_en' => 'Indonesian rupiah'],
    'ILS' => ['name_fr' => 'Nouveau shekel israélien', 'name_en' => 'Israeli new shekel'],
    'INR' => ['name_fr' => 'Roupie indienne', 'name_en' => 'Indian rupee'],
    'IQD' => ['name_fr' => 'Dinar irakien', 'name_en' => 'Iraqi dinar'],
    'IRR' => ['name_fr' => 'Rial iranien', 'name_en' => 'Iranian rial'],
    'ISK' => ['name_fr' => 'Couronne islandaise', 'name_en' => 'Icelandic krona'],
    'JMD' => ['name_fr' => 'Dollar jamaïcain', 'name_en' => 'Jamaican dollar'],
    'JOD' => ['name_fr' => 'Dinar jordanien', 'name_en' => 'Jordanian dinar'],
    'JPY' => ['name_fr' => 'Yen japonais', 'name_en' => 'Japanese yen'],
    'KES' => ['name_fr' => 'Shilling kényan', 'name_en' => 'Kenyan shilling'],
    'KGS' => ['name_fr' => 'Som kirghize', 'name_en' => 'Kyrgyzstani som'],
    'KHR' => ['name_fr' => 'Riel cambodgien', 'name_en' => 'Cambodian riel'],
    'KMF' => ['name_fr' => 'Franc comorien', 'name_en' => 'Comorian franc'],
    'KPW' => ['name_fr' => 'Won nord-coréen', 'name_en' => 'North Korean won'],
    'KRW' => ['name_fr' => 'Won sud-coréen', 'name_en' => 'South Korean won'],
    'KWD' => ['name_fr' => 'Dinar koweïtien', 'name_en' => 'Kuwaiti dinar'],
    'KYD' => ['name_fr' => 'Dollar des îles Caïmans', 'name_en' => 'Cayman Islands dollar'],
    'KZT' => ['name_fr' => 'Tenge kazakh', 'name_en' => 'Kazakhstani tenge'],
    'LAK' => ['name_fr' => 'Kip laotien', 'name_en' => 'Lao kip'],
    'LBP' => ['name_fr' => 'Livre libanaise', 'name_en' => 'Lebanese pound'],
    'LKR' => ['name_fr' => 'Roupie sri-lankaise', 'name_en' => 'Sri Lankan rupee'],
    'LRD' => ['name_fr' => 'Dollar libérien', 'name_en' => 'Liberian dollar'],
    'LSL' => ['name_fr' => 'Loti lésothan', 'name_en' => 'Lesotho loti'],
    'LYD' => ['name_fr' => 'Dinar libyen', 'name_en' => 'Libyan dinar'],
    'MAD' => ['name_fr' => 'Dirham marocain', 'name_en' => 'Moroccan dirham'],
    'MDL' => ['name_fr' => 'Leu moldave', 'name_en' => 'Moldovan leu'],
    'MGA' => ['name_fr' => 'Ariary malgache', 'name_en' => 'Malagasy ariary'],
    'MKD' => ['name_fr' => 'Denar macédonien', 'name_en' => 'Macedonian denar'],
    'MMK' => ['name_fr' => 'Kyat birman', 'name_en' => 'Myanmar kyat'],
    'MNT' => ['name_fr' => 'Tugrik mongol', 'name_en' => 'Mongolian tugrik'],
    'MOP' => ['name_fr' => 'Pataca macanaise', 'name_en' => 'Macanese pataca'],
    'MRU' => ['name_fr' => 'Ouguiya mauritanienne', 'name_en' => 'Mauritanian ouguiya'],
    'MUR' => ['name_fr' => 'Roupie mauricienne', 'name_en' => 'Mauritian rupee'],
    'MVR' => ['name_fr' => 'Rufiyaa maldivienne', 'name_en' => 'Maldivian rufiyaa'],
    'MWK' => ['name_fr' => 'Kwacha malawite', 'name_en' => 'Malawian kwacha'],
    'MXN' => ['name_fr' => 'Peso mexicain', 'name_en' => 'Mexican peso'],
    'MYR' => ['name_fr' => 'Ringgit malaisien', 'name_en' => 'Malaysian ringgit'],
    'MZN' => ['name_fr' => 'Metical mozambicain', 'name_en' => 'Mozambican metical'],
    'NAD' => ['name_fr' => 'Dollar namibien', 'name_en' => 'Namibian dollar'],
    'NGN' => ['name_fr' => 'Naira nigérian', 'name_en' => 'Nigerian naira'],
    'NIO' => ['name_fr' => 'Córdoba nicaraguayen', 'name_en' => 'Nicaraguan cordoba'],
    'NOK' => ['name_fr' => 'Couronne norvégienne', 'name_en' => 'Norwegian krone'],
    'NPR' => ['name_fr' => 'Roupie népalaise', 'name_en' => 'Nepalese rupee'],
    'NZD' => ['name_fr' => 'Dollar néo-zélandais', 'name_en' => 'New Zealand dollar'],
    'OMR' => ['name_fr' => 'Rial omanais', 'name_en' => 'Omani rial'],
    'PAB' => ['name_fr' => 'Balboa panaméen', 'name_en' => 'Panamanian balboa'],
    'PEN' => ['name_fr' => 'Sol péruvien', 'name_en' => 'Peruvian sol'],
    'PGK' => ['name_fr' => 'Kina papou-néo-guinéen', 'name_en' => 'Papua New Guinean kina'],
    'PHP' => ['name_fr' => 'Peso philippin', 'name_en' => 'Philippine peso'],
    'PKR' => ['name_fr' => 'Roupie pakistanaise', 'name_en' => 'Pakistani rupee'],
    'PLN' => ['name_fr' => 'Zloty polonais', 'name_en' => 'Polish zloty'],
    'PYG' => ['name_fr' => 'Guaraní paraguayen', 'name_en' => 'Paraguayan guarani'],
    'QAR' => ['name_fr' => 'Riyal qatari', 'name_en' => 'Qatari riyal'],
    'RON' => ['name_fr' => 'Leu roumain', 'name_en' => 'Romanian leu'],
    'RSD' => ['name_fr' => 'Dinar serbe', 'name_en' => 'Serbian dinar'],
    'RUB' => ['name_fr' => 'Rouble russe', 'name_en' => 'Russian ruble'],
    'RWF' => ['name_fr' => 'Franc rwandais', 'name_en' => 'Rwandan franc'],
    'SAR' => ['name_fr' => 'Riyal saoudien', 'name_en' => 'Saudi riyal'],
    'SBD' => ['name_fr' => 'Dollar des îles Salomon', 'name_en' => 'Solomon Islands dollar'],
    'SCR' => ['name_fr' => 'Roupie seychelloise', 'name_en' => 'Seychellois rupee'],
    'SDG' => ['name_fr' => 'Livre soudanaise', 'name_en' => 'Sudanese pound'],
    'SEK' => ['name_fr' => 'Couronne suédoise', 'name_en' => 'Swedish krona'],
    'SGD' => ['name_fr' => 'Dollar de Singapour', 'name_en' => 'Singapore dollar'],
    'SHP' => ['name_fr' => 'Livre de Sainte-Hélène', 'name_en' => 'Saint Helena pound'],
    'SLE' => ['name_fr' => 'Leone sierra-léonais', 'name_en' => 'Sierra Leonean leone'],
    'SOS' => ['name_fr' => 'Shilling somalien', 'name_en' => 'Somali shilling'],
    'SRD' => ['name_fr' => 'Dollar surinamais', 'name_en' => 'Surinamese dollar'],
    'SSP' => ['name_fr' => 'Livre sud-soudanaise', 'name_en' => 'South Sudanese pound'],
    'STN' => ['name_fr' => 'Dobra santoméen', 'name_en' => 'Sao Tome and Principe dobra'],
    'SYP' => ['name_fr' => 'Livre syrienne', 'name_en' => 'Syrian pound'],
    'SZL' => ['name_fr' => 'Lilangeni eswatinien', 'name_en' => 'Swazi lilangeni'],
    'THB' => ['name_fr' => 'Baht thaïlandais', 'name_en' => 'Thai baht'],
    'TJS' => ['name_fr' => 'Somoni tadjik', 'name_en' => 'Tajikistani somoni'],
    'TMT' => ['name_fr' => 'Manat turkmène', 'name_en' => 'Turkmenistani manat'],
    'TND' => ['name_fr' => 'Dinar tunisien', 'name_en' => 'Tunisian dinar'],
    'TOP' => ['name_fr' => 'Paʻanga tongien', 'name_en' => 'Tongan paʻanga'],
    'TRY' => ['name_fr' => 'Livre turque', 'name_en' => 'Turkish lira'],
    'TTD' => ['name_fr' => 'Dollar de Trinité-et-Tobago', 'name_en' => 'Trinidad and Tobago dollar'],
    'TWD' => ['name_fr' => 'Nouveau dollar taïwanais', 'name_en' => 'New Taiwan dollar'],
    'TZS' => ['name_fr' => 'Shilling tanzanien', 'name_en' => 'Tanzanian shilling'],
    'UAH' => ['name_fr' => 'Hryvnia ukrainienne', 'name_en' => 'Ukrainian hryvnia'],
    'UGX' => ['name_fr' => 'Shilling ougandais', 'name_en' => 'Ugandan shilling'],
    'USD' => ['name_fr' => 'Dollar américain', 'name_en' => 'United States dollar'],
    'UYU' => ['name_fr' => 'Peso uruguayen', 'name_en' => 'Uruguayan peso'],
    'UZS' => ['name_fr' => 'Sum ouzbek', 'name_en' => 'Uzbekistani sum'],
    'VES' => ['name_fr' => 'Bolívar vénézuélien', 'name_en' => 'Venezuelan bolivar'],
    'VND' => ['name_fr' => 'Dong vietnamien', 'name_en' => 'Vietnamese dong'],
    'VUV' => ['name_fr' => 'Vatu vanuatais', 'name_en' => 'Vanuatu vatu'],
    'WST' => ['name_fr' => 'Tala samoan', 'name_en' => 'Samoan tala'],
    'XAF' => ['name_fr' => 'Franc CFA BEAC', 'name_en' => 'Central African CFA franc'],
    'XCD' => ['name_fr' => 'Dollar des Caraïbes orientales', 'name_en' => 'East Caribbean dollar'],
    'XOF' => ['name_fr' => 'Franc CFA BCEAO', 'name_en' => 'West African CFA franc'],
    'XPF' => ['name_fr' => 'Franc CFP', 'name_en' => 'CFP franc'],
    'YER' => ['name_fr' => 'Rial yéménite', 'name_en' => 'Yemeni rial'],
    'ZAR' => ['name_fr' => 'Rand sud-africain', 'name_en' => 'South African rand'],
    'ZMW' => ['name_fr' => 'Kwacha zambien', 'name_en' => 'Zambian kwacha'],
    'ZWG' => ['name_fr' => 'ZiG zimbabwéen', 'name_en' => 'Zimbabwe Gold'],
];

$symbols = [
    'AED' => 'د.إ',
    'AFN' => '؋',
    'ALL' => 'L',
    'AMD' => '֏',
    'ANG' => 'ƒ',
    'AOA' => 'Kz',
    'ARS' => '$',
    'AUD' => '$',
    'AWG' => 'ƒ',
    'AZN' => '₼',
    'BAM' => 'KM',
    'BBD' => '$',
    'BDT' => '৳',
    'BGN' => 'лв',
    'BHD' => '.د.ب',
    'BIF' => 'FBu',
    'BMD' => '$',
    'BND' => '$',
    'BOB' => 'Bs.',
    'BRL' => 'R$',
    'BSD' => '$',
    'BTN' => 'Nu.',
    'BWP' => 'P',
    'BYN' => 'Br',
    'BZD' => '$',
    'CAD' => '$',
    'CDF' => 'FC',
    'CHF' => 'CHF',
    'CLP' => '$',
    'CNY' => '¥',
    'COP' => '$',
    'CRC' => '₡',
    'CUP' => '$',
    'CVE' => '$',
    'CZK' => 'Kč',
    'DJF' => 'Fdj',
    'DKK' => 'kr',
    'DOP' => '$',
    'DZD' => 'د.ج',
    'EGP' => '£',
    'ERN' => 'Nfk',
    'ETB' => 'Br',
    'EUR' => '€',
    'FJD' => '$',
    'FKP' => '£',
    'GBP' => '£',
    'GEL' => '₾',
    'GHS' => '₵',
    'GIP' => '£',
    'GMD' => 'D',
    'GNF' => 'FG',
    'GTQ' => 'Q',
    'GYD' => '$',
    'HKD' => '$',
    'HNL' => 'L',
    'HTG' => 'G',
    'HUF' => 'Ft',
    'IDR' => 'Rp',
    'ILS' => '₪',
    'INR' => '₹',
    'IQD' => 'ع.د',
    'IRR' => '﷼',
    'ISK' => 'kr',
    'JMD' => '$',
    'JOD' => 'د.ا',
    'JPY' => '¥',
    'KES' => 'KSh',
    'KGS' => 'с',
    'KHR' => '៛',
    'KMF' => 'CF',
    'KPW' => '₩',
    'KRW' => '₩',
    'KWD' => 'د.ك',
    'KYD' => '$',
    'KZT' => '₸',
    'LAK' => '₭',
    'LBP' => 'ل.ل',
    'LKR' => 'Rs',
    'LRD' => '$',
    'LSL' => 'L',
    'LYD' => 'ل.د',
    'MAD' => 'د.م.',
    'MDL' => 'L',
    'MGA' => 'Ar',
    'MKD' => 'ден',
    'MMK' => 'K',
    'MNT' => '₮',
    'MOP' => 'P',
    'MRU' => 'UM',
    'MUR' => '₨',
    'MVR' => 'Rf',
    'MWK' => 'MK',
    'MXN' => '$',
    'MYR' => 'RM',
    'MZN' => 'MT',
    'NAD' => '$',
    'NGN' => '₦',
    'NIO' => 'C$',
    'NOK' => 'kr',
    'NPR' => '₨',
    'NZD' => '$',
    'OMR' => 'ر.ع.',
    'PAB' => 'B/.',
    'PEN' => 'S/',
    'PGK' => 'K',
    'PHP' => '₱',
    'PKR' => '₨',
    'PLN' => 'zł',
    'PYG' => '₲',
    'QAR' => 'ر.ق',
    'RON' => 'lei',
    'RSD' => 'дин',
    'RUB' => '₽',
    'RWF' => 'FRw',
    'SAR' => '﷼',
    'SBD' => '$',
    'SCR' => '₨',
    'SDG' => 'ج.س.',
    'SEK' => 'kr',
    'SGD' => '$',
    'SHP' => '£',
    'SLE' => 'Le',
    'SOS' => 'Sh',
    'SRD' => '$',
    'SSP' => '£',
    'STN' => 'Db',
    'SYP' => '£',
    'SZL' => 'L',
    'THB' => '฿',
    'TJS' => 'ЅМ',
    'TMT' => 'm',
    'TND' => 'د.ت',
    'TOP' => 'T$',
    'TRY' => '₺',
    'TTD' => '$',
    'TWD' => '$',
    'TZS' => 'Sh',
    'UAH' => '₴',
    'UGX' => 'USh',
    'USD' => '$',
    'UYU' => '$',
    'UZS' => 'soʻm',
    'VES' => 'Bs.',
    'VND' => '₫',
    'VUV' => 'VT',
    'WST' => 'T',
    'XAF' => 'FCFA',
    'XCD' => '$',
    'XOF' => 'CFA',
    'XPF' => 'F',
    'YER' => '﷼',
    'ZAR' => 'R',
    'ZMW' => 'ZK',
    'ZWG' => 'ZiG',
];

foreach ($currencies as $code => $currency) {
    $currencies[$code]['symbol'] = $symbols[$code] ?? $code;
}

ksort($currencies);

return $currencies;
